version: "3.2"
services:
  nodejs:
    build:
      context: .
    image: node-docker
    ports:
      - "8000:8000"
    networks:
        mynet:
          ipv4_address: 172.25.0.101
    container_name: node-container
  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    # build:
    #   context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
        mynet:
          ipv4_address: 172.25.0.102
    environment:
      - MYSQL_ROOT_PASSWORD=Test123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=aqilliz_db
    container_name: mysql
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
volumes: 
  mysql_data: